FROM node:15.5-alpine as build-stage
ARG REACT_APP_CLIENT_ID
ARG REACT_APP_AGENT_DOMAIN
ARG REACT_APP_REDIRECT_URI
ARG REACT_APP_EVM_HOST
ARG REACT_APP_NODE_HOST

ENV REACT_APP_CLIENT_ID ${REACT_APP_CLIENT_ID}
ENV REACT_APP_AGENT_DOMAIN ${REACT_APP_AGENT_DOMAIN}
ENV REACT_APP_REDIRECT_URI ${REACT_APP_REDIRECT_URI}
ENV REACT_APP_EVM_HOST ${REACT_APP_EVM_HOST}
ENV REACT_APP_NODE_HOST ${REACT_APP_NODE_HOST}

WORKDIR /app

COPY . /app

RUN npm i
RUN npm run build

FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

